# -*- coding: utf-8 -*-

db.define_table('ficha_clinica_mulher',
             Field('id_paciente', 'reference pacientes',
                   writable=False,readable=False),
             Field('queixa', type='text', label='Queixa', ),
             Field('hpma', type='text', label='HPMA', ),
             Field('cardiovascular_ISDA', label='Cardiovascular', ),
             Field('gastrointestinal_ISDA', label='Gastrointestinal', ),
             Field('urinario_ISDA', label='Urinário', ),
             Field('respiratorio_ISDA', label='Respiratório', ),
             Field('cardiovascular_AF', label='Cardiovascular', ),
             Field('endocrino_metabolico_AF', label='Endócrino metabólico', ),
             Field('cancer_AF', label='Câncer', ),
             Field('infeccao_AF', label='Infecção', ),
             Field('outros_AF', label='Outros', ),
             Field('clinicos_AP', label='Clínicos', ),
             Field('cirurgias_AP', label='Cirurgias', ),
             Field('tabagismo_AP', label='Tabagismo', ),
             Field('etilismo_AP', label='Etilismo', ),
             Field('medicacao_AP', label='Medicações', ),
             Field('outros_AP', label='Outros', ),
             Field('menarca_AM', label='Menarca', ),
             Field('ciclos_AM', label='Ciclos', ),
             Field('dum_AM', label='DUM', ),
             Field('dismenorreia_AM', label='Dismenorréia', ),
             Field('tpm_AM', label='TPM', ),
             Field('menopausa_AM',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Natural','Cirúrgica'])),
                   widget=SQLFORM.widgets.radio.widget,
                   label='Menopausa'),
             Field('primeiro_coito_AS', label='1º Coito', ),
             Field('numero_parceiros_AS', label='Nº Parceiros', ),
             Field('libido_AS', label='Libido', ),
             Field('orgasmos_AS', label='Orgasmos', ),
             Field('anticoncepcao_AS', label='Anticoncepção', ),
             Field('corrimento_AG', label='Corrimento', ),
             Field('cirurgia_AG', label='Cirurgia', ),
             Field('cauterizacao_AG', label='Cauterização', ),
             Field('g_AO', label='G', ),
             Field('p_AO', label='P', ),
             Field('a_AO', label='A', ),
             Field('pnl_AO', label='PNL', ),
             Field('pc_AO', label='PC', ),
             Field('pf_AO', label='PF', ),
             Field('primeiro_parto_AO', label='1º parto', ),
             Field('ultimo_parto_AO', label='Último parto', ),
             Field('peso_rn_maior_AO', label='Peso RN (maior)', ),
             Field('amamentacao_AO', label='Amamentação', ),
             Field('puerperio_AO', label='Puerpério', ),
             Field('peso_EXAME', label='Peso', ),
             Field('alt_EXAME', label='Alt', ),
             Field('pa_EXAME', label='PA', ),
             Field('imc_EXAME', label='IMC', ),
             Field('ap_cardiovascular_EXAME', label='Ap. Cardiovascular', ),
             Field('ap_respiratorio_EXAME', label='Ap. Respiratório', ),
             Field('mmii_EXAME', label='MMII', ),
             Field('outros_EXAME', label='Outros', ),
             Field('abdome_EXAME', label='Abdome', ),
             Field('insp_estatica_MAMAS', label='Insp. Estática', ),
             Field('insp_dinamica_MAMAS', label='Insp. Dinâmica', ),
             Field('palpacao_MAMAS', label='Palpação', ),
             Field('expressao_MAMAS', label='Expressão', ),
             Field('axilas_MAMAS', label='Axilas', ),
             Field('pilificacao_OGE', label='Pilificação', ),
             Field('labios_OGE', label='Lábios', ),
             Field('clitoris_OGE', label='Clitóris', ),
             Field('ureta_OGE', label='Uretra', ),
             Field('gl_bartholin_OGE', label='Gl. Bartholin', ),
             Field('himen_OGE', label='Hímen', ),
             Field('procidencia_pva_OGE', label='Procidência PVA', ),
             Field('procidencia_pvp_OGE', label='Porcidência PVP', ),
             Field('perineo', label='Períneo', ),
             Field('perda_urina', label='Perda Urina', ),
             Field('vagina_OGI_TOQUE', label='Vagina', ),
             Field('colo_OGI_TOQUE', label='Colo', ),
             Field('utero_OGI_TOQUE', label='Últero', ),
             Field('an_d_OGI_TOQUE', label='AN. D', ),
             Field('na_e_OGI_TOQUE', label='NA. E', ),
             Field('parametrios_OGI_TOQUE', label='Paramétrios', ),
             Field('reto_OGI_TOQUE', label='Reto', ),
             Field('vagina_ESPECULAR', label='Vagina', ),
             Field('colo_ESPECULAR', label='Colo', ),
             Field('cont_vaginal_ESPECULAR', label='Cont. Vaginal', ),
             Field('tracao_colo_OUTROS_EXAMES', label='Tração do colo', ),
             Field('histerometria_OUTROS_EXAMES', label='Histerometria', ),
             Field('diagnostico_clinico_OUTROS_EXAMES', label='Diagnóstico clínico', ),
             Field('exames_solicitados_OUTROS_EXAMES', label='Exames solicitados', ),
             Field('conduta_OUTROS_EXAMES', label='Conduta', ),
),

db.define_table('ficha_clinica_de_climaterio',
             Field('id_paciente', 'reference pacientes',
                    writable=False,readable=False),
             Field('motivo_consulta', type='text', label='Motivo da consulta', ),
             Field('hipertensao', widget=SQLFORM.widgets.boolean.widget, label='Hipertensão', ),
             Field('hipertensao_texto', label='', ),
             Field('tireoidopatia', widget=SQLFORM.widgets.boolean.widget, label='Tireoidopatia', ),
             Field('tireoidopatia_texto', label='', ),
             Field('tromboflebite', widget=SQLFORM.widgets.boolean.widget, label='Tromboflebite', ),
             Field('tromboflebite_texto', label='', ),
             Field('gastriste_colocistopatia',
                   widget=SQLFORM.widgets.boolean.widget, ),
             Field('gastriste_colocistopatia_texto', label='Gastrite colocistopatia', ),
             Field('doenca_cardio_cerebrovascular',
                   widget=SQLFORM.widgets.boolean.widget ),
             Field('doenca_cardio_cerebrovascular_texto', label='Doença Cardio-Cerebrovascular', ),
             Field('nefropatia', widget=SQLFORM.widgets.boolean.widget, label='Nefropatia', ),
             Field('nefropatia_texto', label='Nefropatia', ),
             Field('cirugia', widget=SQLFORM.widgets.boolean.widget, label='Cirugia', ),
             Field('cirugia_texto', label='Cirurgia', ),
             Field('tabagismo', widget=SQLFORM.widgets.boolean.widget, label='Tabagismo', ),
             Field('tabagismo_texto', label='Tabagismo', ),
             Field('medicacao_em_uso',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('medicacao_em_uso_texto', label='Medicação em uso' , ),
             Field('atividade_fisica',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('atividade_fisica_texto', label='Atividade física' , ),
             Field('hepatopatia', widget=SQLFORM.widgets.boolean.widget, label='Hepatopatia', ),
             Field('hepatopatia_texto', label='Hepatopatia', ),
             Field('cancer', widget=SQLFORM.widgets.boolean.widget, label='Câncer', ),
             Field('cancer_texto', label='Câncer', ),
             Field('etilismo', widget=SQLFORM.widgets.boolean.widget, label='Etilismo', ),
             Field('etilismo_texto', label='Etilismo', ),
             Field('neuro_psquiatrico',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('neuro_psquiatrico_texto', label='Neuro psiquiatrico', ),
             Field('cancer_de_mama',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_ovario',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_utero',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_colon',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('osteoporose', widget=SQLFORM.widgets.boolean.widget, label='Osteoporose', ),
             Field('cardio_cerebrovascular',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('outros_AF', widget=SQLFORM.widgets.boolean.widget, label='Outros', ),
             Field('menarca', widget=SQLFORM.widgets.boolean.widget, label='Menarca', ),
             Field('menarca_texto', label='Menarca', ),
             Field('ciclos_regulares',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('ciclos_regulares_texto', label='Ciclos regulares', ),
             Field('atividade_sexual',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('atividade_sexual_texto', label='Atividade sexual', ),
             Field('dum', label='DUM', ),
             Field('g_AT', label='G', ),
             Field('p_AT', label='P', ),
             Field('a_AT', label='A', ),
             Field('pnl_AT', label='PNL', ),
             Field('pc_AT', label='PC', ),
             Field('pf_AT', label='PF', ),
             Field('idade_menopausa', label='Idade Menopausa', ),
             Field('tempo_menopausa', label='Tempo de Menopausa', ),
             Field('tipo_menopausa',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Natural',
                                                   'Cirúrgica',
                                                   'Radioterápica',
                                                   'Quimioterápia']),),),
             Field('histerectomia', widget=SQLFORM.widgets.boolean.widget, label='Histerectomia', ),
             Field('ooforectoma_bilateral',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('pipula', widget=SQLFORM.widgets.boolean.widget, label='Pilula', ),
             Field('pipula_texto', label='Pilula', ),
             Field('reposicao_hormonal',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('reposicao_hormonal_texto', label='Reposição hormonla', ),
             Field('peso', label='Peso', ),
             Field('altura', label='Altura', ),
             Field('imc', label='IMC', ),
             Field('pa', label='PA', ),
             Field('MAMAS_inspecao', label='Mamas: Inspeção', ),
             Field('MAMAS_palpacao', label='Palpação', ),
             Field('MAMAS_axila', label='Axila', ),
             Field('abdome', label='Abdome', ),
             Field('oge', label='OGE', ),
             Field('ogi_vagina', label='OGI – Vagina', ),
             Field('colo', label='Colo', ),
             Field('corpo_do_utero', label='Corpo do útero', ),
             Field('anexos', label='Anexos', ),
             Field('toque_retal', label='Toque retal', ),
             Field('teste_progesterona',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Positivo',
                                                   'Negativo']),),
                   widget=SQLFORM.widgets.radio.widget),
             Field('teste_progesterona_data', label='Data', ),
             Field('colpocitologia_oncologica', label='Colpocitologia oncológica', ),
             Field('im', label='IM', ),
             Field('im_data', label='IM Data', ),
             Field('mamografia', label='Mamografia', ),
             Field('mamografia_data', label='Data', ),
             Field('glicemia', label='Glicemia', ),
             Field('colesterou_total', label='Colesterou total', ),
             Field('hdl', label='HDL', ),
             Field('ldl', label='LDL', ),
             Field('triglicerides', label='Triglicérides', ),
             Field('ultra_sonografia_transvaginal', label='Ultra-sonografia transvaginal', ),
             Field('ultra_sonografia_transvaginal_data', label='Data', ),
             Field('densitometria_ossea', label='Densitometria óssea', ),
             Field('densitometria_ossea_data', label='Data', ),
             Field('dosagens_hormonais', label='Dosagens Hormonais', ),
             Field('dosagens_hormonais_data', label='Data', ),
             Field('consulta_outro_especialista',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('consulta_outro_especialista_texto', label='Consulta outro especialista', ),
             Field('diagnostico_clinico', type='text', label='Diagnóstico clínico', ),
             Field('orientacao_terapeutica', type='text', label='Orientação terapêutica', ),
             Field('data_EVOLUCAO', label='Data', ),
             Field('pa_EVOLUCAO', label='PA', ),
             Field('peso_EVOLUCAO', label='Peso', ),
             Field('altura_EVOLUCAO', label='Altura', ),
             Field('imc_EVOLUCAO', label='IMC', ),
             Field('texto_EVOLUCAO', type='text', label='Observações', ),
),


db.define_table('ficha_clinica_de_anticoncepcao',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
                Field('queixa', type='text', label='Queixa', ),
                Field('hpma', type='text', label='HPMA', ),
                Field('hipertensao_arterial_AF',
                    widget=SQLFORM.widgets.boolean.widget, label='Hipertensão arterial', ),
                Field('diabetes_AF', widget=SQLFORM.widgets.boolean.widget, label='Diabetes', ),
                Field('cardiopatia_AF',
                    widget=SQLFORM.widgets.boolean.widget, label='Cardiopatia', ),
                Field('cancer_AF', widget=SQLFORM.widgets.boolean.widget, label='Câncer', ),
                Field('tipo_cancer_AF', label='Tipo', ),
                Field('neurologico_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Neurológico', ),
                Field('cardiovasculares_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Cardiovasculares', ),
                Field('hipertensao_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Hipertensão', ),
                Field('flebites_AP', widget=SQLFORM.widgets.boolean.widget, label='Flebites', ),
                Field('trombose_venosa_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Trombose venosa', ),
                Field('diabetes_AP', widget=SQLFORM.widgets.boolean.widget, label='Diabetes', ),
                Field('tireoide_AP', widget=SQLFORM.widgets.boolean.widget, label='Tireóideide', ),
                Field('outras_AP', widget=SQLFORM.widgets.boolean.widget, label='Outras' ),
                Field('hepatite_AP', widget=SQLFORM.widgets.boolean.widget, label='Hepatite', ),
                Field('colecistopatias_AP', widget=SQLFORM.widgets.boolean.widget, label='Colecistopatias', ),
                Field('gonococcia_AP', widget=SQLFORM.widgets.boolean.widget, label='Gonococcia', ),
                Field('sifilis_AP', widget=SQLFORM.widgets.boolean.widget, label='Sifilis', ),
                Field('hpv_AP', widget=SQLFORM.widgets.boolean.widget, label='HPV', ),
                Field('hiv_AP', widget=SQLFORM.widgets.boolean.widget, label='HIV', ),
                Field('cardiopatia_AP', widget=SQLFORM.widgets.boolean.widget, label='Cardiopatia', ),
                Field('outras_dst_AP', label='Outras', ),
                Field('doencas_renais_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='D. Renais', ),
                Field('doencas_hematologicas_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='D. Hematologicas', ),
                Field('anemia_AP', widget=SQLFORM.widgets.boolean.widget, label='Anemia', ),
                Field('a_falciforme_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='A. Falciforme', ),
                Field('outras_doencas_AP', label='Outras', ),
                Field('cancer_AP', widget=SQLFORM.widgets.boolean.widget, label='Câncer', ),
                Field('cirurgias_anteriores_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Cirurgias anteriores', ),
                Field('alergias_AP', widget=SQLFORM.widgets.boolean.widget, label='Alergias', ),
                Field('transfusao_AP', widget=SQLFORM.widgets.boolean.widget, label='Transfusão', ),
                Field('tranquilizantes_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Tranquilizantes', ),
                Field('antidepressivos_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Antidepressivos', ),
                Field('antibioticos_AP',
                    widget=SQLFORM.widgets.boolean.widget, label='Antibióticos', ),
                Field('outros_medicacao_atual_AP', label='Outros', ),
                Field('menarca_AM', label='Menarca', ),
                Field('dum_AM', label='Dum', ),
                Field('dismenorreia_AM',
                        widget=SQLFORM.widgets.boolean.widget, label='Dismenorréia', ),
                Field('tpm_AM', widget=SQLFORM.widgets.boolean.widget, label='TMP', ),
                Field('ciclo_menstrual_AM', label='Ciclo Menstrual', ),
                Field('gesta_AO', label=' Gesta', ),
                Field('para_AO', label='Para', ),
                Field('espontaneos_AO', label='Espontâneos', ),
                Field('provocados_AO', label='Provocados', ),
                Field('ultimo_aborto_AO', label='Último aborto', ),
                Field('intercorrencias_AO', label='Intercorrências', ),
                Field('normais_AO', label='Normais', ),
                Field('cesareas_AO', label='Cesáreas', ),
                Field('forcepes_AO', label='Fórcepes', ),
                Field('primeiro_parto_AO', label='Primeiro parto', ),
                Field('ultimo_parto_AO', label='Último parto', ),
                Field('aleitamento_AO', label='Aleitamento', ),
                Field('idade_primeira_relacao_HS', label='Idade da primeira relação', ),
                Field('durante_ano_HS', label='Durante todo ano', ),
                Field('ultimos_meses_HS', label='Ultimos meses', ),
                Field('frequencia_relacoes_sexuais_HS', requires=IS_EMPTY_OR(
                    IS_IN_SET(['nenhuma', '1 relação semana',
                        '2 relações semana', '3 - 5 relações semana',
                        '5 relações semana', 'eventual semana']))),
                Field('orgamos_HS', widget=SQLFORM.widgets.boolean.widget, label='Orgasmos', ),
                Field('dispareunia_HS', widget=SQLFORM.widgets.boolean.widget, label='Dispareunia', ),
                Field('coito_anal_HS', widget=SQLFORM.widgets.boolean.widget, label='Coito Anal', ),
                Field('tabagismo_HS', widget=SQLFORM.widgets.boolean.widget, label='tabagismo', ),
                Field('etilismo_HS', widget=SQLFORM.widgets.boolean.widget, label='Etilismo', ),
                Field('drogas_HS', widget=SQLFORM.widgets.boolean.widget, label='Drogas', ),
                Field('drogas_qual_HS', label='Qual', ),
                Field('drogas_injetaveis_HS',label='Injetável', ),
                Field('ritmo_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ritmo', ),
                Field('ritmo_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ritmo', ),
                Field('ritmo_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ritmo', ),
                Field('diafragma_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Diafragma', ),
                Field('diafragma_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Diafragma', ),
                Field('diafragma_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Diafragma', ),
                Field('geleia_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Geléia', ),
                Field('geleia_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Geléia', ),
                Field('geleia_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Geléia', ),
                Field('preservativo_masculino_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Preservativo Masculino', ),
                Field('preservativo_masculino_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Preservativo Masculino', ),
                Field('preservativo_masculino_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Preservativo Masculino', ),
                Field('camisinha_feminina_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Camisinha Feminina', ),
                Field('camisinha_feminina_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Camisinha Feminina', ),
                Field('camisinha_feminina_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Camisinha Feminina', ),
                Field('diu_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='DIU', ),
                Field('diu_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='DIU', ),
                Field('diu_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='DIU', ),
                Field('pilula_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Pílula', ),
                Field('pilula_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Pílula', ),
                Field('pilula_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Pílula', ),
                Field('injetavel_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Injetável', ),
                Field('injetavel_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Injetável', ),
                Field('injetavel_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Injetável', ),
                Field('ligadura_tubaria_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ligadura', ),
                Field('ligadura_tubaria_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ligadura', ),
                Field('ligadura_tubaria_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Ligadura', ),
                Field('vasectomia_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Vasectomia', ),
                Field('vasectomia_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Vasectomia', ),
                Field('vasectomia_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget, label='Vasectomia',),
                Field('qual_CAP', label='Qual', ),
                Field('quanto_tempo_CAP', label='Quanto tempo', ),
                Field('metodo_escolha_pacientes', label='Metodo de escolha',),
                Field('indicacao_medica', label='Indicação médica', ),
                Field('metodo_anticoncepcional', label='Método anticoncepcional', ),
                Field('observacoes', type='text', label='Observações', ),
                ),


db.define_table('ficha_clinica_mastologia',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('d_QD', widget=SQLFORM.widgets.boolean.widget, label='D', ),
             Field('e_QD', widget=SQLFORM.widgets.boolean.widget, label='E', ),
             Field('tempo_meses_QD', label='Tempo em meses', ),
             Field('nodulo_QD', widget=SQLFORM.widgets.boolean.widget, label='Nódulo', ),
             Field('dor_QD', widget=SQLFORM.widgets.boolean.widget, label='Dor', ),
             Field('fluxo_QD', widget=SQLFORM.widgets.boolean.widget, label='Fluxo', ),
             Field('inflamacao_QD', widget=SQLFORM.widgets.boolean.widget, label='Inflamação', ),
             Field('treuma_QD', widget=SQLFORM.widgets.boolean.widget, label='Trauma', ),
             Field('assintomatica_QD', widget=SQLFORM.widgets.boolean.widget, label='Issintomática', ),
             Field('outros_QD', label='Outros', ),
             Field('observacoes_QD', label='Observações', ),
             Field('menarca_AT', label='Menarca', ),
             Field('idade_primeiro_AT', label='Idade primeiro', ),
             Field('menopausa_AT', label='Menopausa', ),
             Field('aleitamente_numero_total_AT', label='Aleitamento Nº. total (meses)', ),
             Field('hormonios_AT', widget=SQLFORM.widgets.boolean.widget, label='Hormônios', ),
             Field('dum_AT', label='DUM', ),
             Field('aco_AT', widget=SQLFORM.widgets.boolean.widget, label='ACO', ),
             Field('aco_text_AT', label='ACO', ),
             Field('g_AT', label='G', ),
             Field('p_AT', label='P', ),
             Field('a_AT', label='A', ),
             Field('trh_AT', widget=SQLFORM.widgets.boolean.widget, label='THR', ),
             Field('trh_text_AT', label='THR', ),
             Field('alcoolismo_APF', widget=SQLFORM.widgets.boolean.widget, label='Alcoolismo',),
             Field('alcoolismo_text_APF', label='Alcoolismo', ),
             Field('tabagismo_APF', widget=SQLFORM.widgets.boolean.widget, label='Tabagismo',),
             Field('tabagismo_text_APF', label='Tabagismo', ),
             Field('biopsia_previa_APF',
                 widget=SQLFORM.widgets.boolean.widget, label='Biopsia', ),
             Field('ap_APF', label='AP', ),
             Field('cancer_mama_APF', widget=SQLFORM.widgets.boolean.widget, label='Câncer de mama', ),
             Field('tratamento', requires=IS_EMPTY_OR(
                 IS_IN_SET(['conservador', 'radical', 'RT', 'QT', 'HT']))),
             Field('mae_CM', widget=SQLFORM.widgets.boolean.widget, label='Mãe', ),
             Field('materno_CM', widget=SQLFORM.widgets.boolean.widget, label='Materno', ),
             Field('unilateral_CM', widget=SQLFORM.widgets.boolean.widget, label='Unilateral', ),
             Field('avo_CM', widget=SQLFORM.widgets.boolean.widget, label='Avó', ),
             Field('paterno_CM', widget=SQLFORM.widgets.boolean.widget, label='Paterno', ),
             Field('bilateral_CM', widget=SQLFORM.widgets.boolean.widget, label='Bilateral', ),
             Field('tia_CM', widget=SQLFORM.widgets.boolean.widget, label='Tia', ),
             Field('irma_CM', widget=SQLFORM.widgets.boolean.widget, label='Irmã', ),
             Field('prima_CM', widget=SQLFORM.widgets.boolean.widget, label='Prima', ),
             Field('idade_CM', label='Idade', ),
             Field('observacoes_CM', label="Observações", ),
             Field('endometrio_OC', widget=SQLFORM.widgets.boolean.widget, label='Endométrio', ),
             Field('colon_OC', widget=SQLFORM.widgets.boolean.widget, label='Cólon', ),
             Field('ovario_OC', widget=SQLFORM.widgets.boolean.widget, label='Ovário', ),
             Field('tireoide_OC', widget=SQLFORM.widgets.boolean.widget, label='Tireóide', ),
             Field('prostata_OC', widget=SQLFORM.widgets.boolean.widget, label='Próstata', ),
             Field('outros_OC', widget=SQLFORM.widgets.boolean.widget, label='Outros', ),
             Field('outros_text_OC', label="Outros", ),
             Field('exame_fisico_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado', 'D', 'E']))),
             Field('inspecao_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'volume', 'P', 'M', 'G']))),
             Field('abaulamento_E', widget=SQLFORM.widgets.boolean.widget, label='Abaulamento', ),
             Field('retracao_E', widget=SQLFORM.widgets.boolean.widget, label='Retração', ),
             Field('uiceracao_E', widget=SQLFORM.widgets.boolean.widget, label='Ulceração', ),
             Field('eritema_E', widget=SQLFORM.widgets.boolean.widget, label='Eritema', ),
             Field('edema_E', widget=SQLFORM.widgets.boolean.widget, label='Edema', ),
             Field('edema_braco_E', widget=SQLFORM.widgets.boolean.widget, label='Edema braço', ),
             Field('palpacao_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'espessamento', 'nodulo']))),
             Field('consistencia_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['cistica', 'endurecimento', 'fibroelastico', 'lipomatosa']))
                 ),
             Field('mobilidade_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['móvel', 'fixo', 'Fáscia peitoral', 'Parede costal', 'pele']
                 ))),
             Field('superficie_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['regular', 'irregular']))),
             Field('fluxo_Ex', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['S', 'N', 'D', 'E']))),
             Field('cor_Ex', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['sangue', 'sero-sanguinolento', 'seroso', 'esverdeado',
                     'lacteo', 'cristalino']))),
             Field('multiductal_Ex', widget=SQLFORM.widgets.boolean.widget, label='Multiductal', ),
             Field('uniductal_Ex', widget=SQLFORM.widgets.boolean.widget, label='Uniductal', ),
             Field('linfonodos_axila_Ex',
                     widget=SQLFORM.widgets.boolean.widget, label='Linfonodos Axila', ),
             Field('supre_clavicular_Ex',
                     widget=SQLFORM.widgets.boolean.widget, label='Surpre-Clavicular', ),
             Field('d_Ex', widget=SQLFORM.widgets.boolean.widget, label='D', ),
             Field('unico_Ex', widget=SQLFORM.widgets.boolean.widget, label='Unico', ),
             Field('moveis_Ex', widget=SQLFORM.widgets.boolean.widget, label='Móveis', ),
             Field('isolado_Ex', widget=SQLFORM.widgets.boolean.widget, label='Isolado', ),
             Field('e_Ex', widget=SQLFORM.widgets.boolean.widget, label='E', ),
             Field('multiplo_Ex', widget=SQLFORM.widgets.boolean.widget,label='Múltiplo', ),
             Field('fixos_Ex', widget=SQLFORM.widgets.boolean.widget, label='Fixos', ),
             Field('conglomerado_Ex', widget=SQLFORM.widgets.boolean.widget, label='Conglomerado', ),
             Field('lesao_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 [1, 2, 3, 'D', 'E']))),
             Field('suspeita_clinica_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('mamografia_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('usg_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('citologia_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('paaf_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('bag_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('biopsia_SC', widget=SQLFORM.widgets.boolean.widget, label='Biópsia', ),
             Field('ap_SC', label='AP', ),
             Field('estadiamento_clinico', label='Estadiamento', ),
             Field('tnm', label='TNM', ),
             Field('conduta', label='Conduta', ),
             Field('rx_torax', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('rx_torax_text'),
             Field('mapeamento_osseo', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('mapeamento_osseo_text'),
             Field('usg_abdominal', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('usg_abdominal_text'),
             Field('usg_pelvica', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('usg_pelvica_text'),
            ),


db.define_table('ficha_clinica_parto_e_puerperio',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('data_P', label='Data', ),
             Field('local_P', label='Local', ),
             Field('nivel_atencao_P', label='Nivel Atenção', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['1 º', '2º', '3º', 'Domiciliar', 'Outro']))),
             Field('idade_gestacional_P', label='Idade gestacional', ),
             Field('inicio_P',  label='Inicio', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Espontâneo', 'Induzido']))),
             Field('tipo_parto_P', label='Tipo Parto', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Fórcepe', 'Cesária', 'Cefálico', 'Pélvico',
                     'Único', 'Gemelar']))),
             Field('episiotomia_P', widget=SQLFORM.widgets.boolean.widget, label='Episiotomia', ),
             Field('laceracao_P', widget=SQLFORM.widgets.boolean.widget, label='Laceração', ),
             Field('delivramento_espontaneo_P',
                 widget=SQLFORM.widgets.boolean.widget, label='Delivramento', ),
             Field('curagem_P', widget=SQLFORM.widgets.boolean.widget, label='Curagem', ),
             Field('mae_rh_P', widget=SQLFORM.widgets.boolean.widget, label='Mãe RH(-)', ),
             Field('imunoglobulina_P', widget=SQLFORM.widgets.boolean.widget, label='Imunoglobina',  ),
             Field('responsavel_parto_P', label='Responsávelvel pelo Parto', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Médico', 'Enfermeira', 'Auxiliar']))),
             Field('responsavel_outro_P', label='Responsávelvel pelo parto', ),
             Field('morte_fetal_P', widget=SQLFORM.widgets.boolean.widget, label='Morte fetal', ),
             Field('morte_feta_gestacao_P',
                 widget=SQLFORM.widgets.boolean.widget, label='Gestação', ),
             Field('morte_feta_parto_P',
                 widget=SQLFORM.widgets.boolean.widget, label='Parto', ),
             Field('morte_feta_ignorado_P',
                 widget=SQLFORM.widgets.boolean.widget,  label='Ignorado', ),
             Field('morte_feta_causa_P', label='Causa' ),
             Field('medicaocoes_parto_P', type='text', label='Medicações parto', ),
             Field('intercorrencias_parto_P', type='text', label='Intercorrências parto', ),
             Field('sexo_RN', label='Sexo',
                 requires=IS_EMPTY_OR(IS_IN_SET(['Masculino', 'Feminino']))),
             Field('apgar_RN', label='Apgar',
                 requires=IS_EMPTY_OR(IS_IN_SET(['1º minuto', '5º minuto']))),
             Field('reanimacao_P', widget=SQLFORM.widgets.boolean.widget, label='Reanimação', ),
             Field('vdrl_P', widget=SQLFORM.widgets.boolean.widget, label='VDRL', ),
             Field('tipagem_sanguinea_P', label='Tipagem Sanguinea', ),
             Field('peso_P', label='Peso', ),
             Field('idade_exame_fisico_P', label='Idade do exame físico', ),
             Field('peso_idade_gestacional_P', label='Peso Idade Gestacional', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['AIG', 'GIG', 'PIG']))),
             Field('exame_fisico_P', label='Exame físico', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Anormal']))),
             Field('exame_neurologico_P', label='Exame Neurológico', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Anormal']))),
             Field('estatura_P', label='Estatura', ),
             Field('perimetro_cefalico_P', label='Perímetrometro cefálico', ),
             Field('achados_anormais_P', type='text', label='Achados anormais', ),
             Field('alojamento_conjunto_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Alojamento conjunto', ),
             Field('patologias_intercorrentes_memb_hialina_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Memb Hialina', ),
             Field('patologias_intercorrentes_hemorragia_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Hemorragia', ),
             Field('patologias_intercorrentes_anomalia_congenita_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Anomalia Congenita',),
             Field('patologias_intercorrentes_aspiracao_meconial_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Aspiração Meconial',),
             Field('patologias_intercorrentes_hiperbilirrubinemia_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Hiperbilirrubineia',),
             Field('patologias_intercorrentes_apneia_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Apneia',),
             Field('patologias_intercorrentes_outras_sindromes_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Outras Sindromes',),
             Field('patologias_intercorrentes_convuncao_P',
                     widget=SQLFORM.widgets.boolean.widget, label='Convunção',),
             Field('patologias_intercorrentes_outras_P', type='text', label='Outras'),
             Field('alta_rn_P', label='Alta RN', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Sadio', 'Transferido']))),
             Field('idadei_alta_P', label='Idade alta', ),
             Field('transferencias_P', label='Transferência',requires=IS_EMPTY_OR(IS_IN_SET(
                 ['+ 24', '- 24']))),
             Field('transferencias_dias_P', label='Transferência Dias', ),
             Field('idade_obito_dias_P', label='Idade óbito Dias', ),
             Field('idade_obito_horas_P', label='Idade óbito Hora', ),
             Field('causa_obito_P', type='text', label='Causa óbito', ),
             Field('sexo_P', label='Sexo', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Masculino', 'Feminino']))),
             Field('alimentacao_P', label='Alimentação', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Mama', 'Mista', 'Artificial']))),
             Field('data_CP', label='DataCP', ),
             Field('queixas_CP', type='text', label='Queixas', ),
             Field('pa_CP', label='PA', ),
             Field('estado_geral_CP', label='Estado geral', ),
             Field('mucosa_CP', label='Mucosa', ),
             Field('mamas_CP', label='Mamas', ),
             Field('abdome_CP', label='Abdome', ),
             Field('exame_ginecologico_CP', label='Exame ginecologico', ),
             Field('aleitamento_materno_CP',
                     widget=SQLFORM.widgets.boolean.widget, label='Aleitamento materno', ),
             Field('barreira_CP', widget=SQLFORM.widgets.boolean.widget, label='Barreira', ),
             Field('diu_CP', widget=SQLFORM.widgets.boolean.widget, label='DIU', ),
             Field('hormonal_oral_CP', widget=SQLFORM.widgets.boolean.widget, label='Hormonla oral', ),
             Field('hormonal_injetavel_CP',
                     widget=SQLFORM.widgets.boolean.widget, label='Hormonal injetável', ),
             Field('comportamental_CP',
                     widget=SQLFORM.widgets.boolean.widget, label='Comportamental', ),
             Field('cirurgico_CP', widget=SQLFORM.widgets.boolean.widget, label='Cirúrgico', ),
             Field('nenhum_CP', widget=SQLFORM.widgets.boolean.widget, label='Nenhum', ),
             Field('orientacao_CP', type='text', label='Orientação/Conduta', ),
            ),


db.define_table('ficha_clinica_pre_natal',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
            Field('data', type='date', default=request.now,
                  readable=False, writable=False),
             Field('AF_hipertencao_arterial_A',
                 widget=SQLFORM.widgets.boolean.widget, label='Hipertenção arterial', ),
             Field('AF_diabetes_A', widget=SQLFORM.widgets.boolean.widget, label='Diabetes', ),
             Field('AF_gemelidade_A', widget=SQLFORM.widgets.boolean.widget, label='Gemelidade', ),
             Field('AF_malformacao_A', widget=SQLFORM.widgets.boolean.widget, label='Malformação', ),
             Field('AF_outros_A', label='Outros', ),
             Field('AP_hipertencao_arterial_A',
                 widget=SQLFORM.widgets.boolean.widget, label='Hipertenção arterial', ),
             Field('AP_diabetes_A', widget=SQLFORM.widgets.boolean.widget, label='Diabetes', ),
             Field('AP_cir_pelvica_A', widget=SQLFORM.widgets.boolean.widget, label='Cir.Pélvica', ),
             Field('AP_cardiopatia_A', widget=SQLFORM.widgets.boolean.widget, label='Cardiopatia', ),
             Field('AP_infc_urinaria_A',
                 widget=SQLFORM.widgets.boolean.widget, label='Infec.Urinária', ),
             Field('AP_malformacao_A', widget=SQLFORM.widgets.boolean.widget, label='Malformação', ),
             Field('AP_outros_A', label='Outros',  ),
             Field('gestacao_AO', label='Gestação', ),
             Field('parto_AO', label='Parto', ),
             Field('abortos_AO', label='Abortos', ),
             Field('ectopicas_AO', label='Ectópicas', ),
             Field('gemelares_AO', label='Gemelares', ),
             Field('abortamentos_AO', label='Abortamentos', ),
             Field('espontaneos_AO', label="Espontâneos", ),
             Field('provocados_AO', label='Provocadosao', ),
             Field('com_curetagem_AO', label='Com curetagem', ),
             Field('partos_vaginais_AO', label='Partos vaginais', ),
             Field('partos_cesarios_AO', label='Cesáreos', ),
             Field('nascidos_vivos_AO', label='Nascidos vivos', ),
             Field('nascidos_mortos_AO', label='Nascidos mortos', ),
             Field('filhos_vivos_atuais_AO', label='Filhos vivos atuais', ),
             Field('obitos_primeira_semana_AO', label='Obitos 1ª semana', ),
             Field('obitos_apos_primeira_semana_AO', label='Obitos apos 1ª semana', ),
             Field('causa_obitos_AO', label='Causa do obito', ),
             Field('peso_rn_AO', label='Peso RN', ),
             Field('data_ultima_gestacao_AO', label='Data da ultima gestacao', ),
             Field('amamentacao_AO', widget=SQLFORM.widgets.boolean.widget, label='Amamentação', ),
             Field('amamentacao_duracao_AO', label='Duracao', ),
             Field('amamentacao_causa_insucesso_AO', label='Causa insucesso', ),
             Field('intercorrencias_gestacoes_anteriores_AO',label='Intercorrencias em gestações anteriores', ),
             Field('dum_GA', label='DUM', ),
             Field('dpp_GA', label='DPP', ),
             Field('duvida_GA', widget=SQLFORM.widgets.boolean.widget, label='Dúvida', ),
             Field('duvida_qual_GA', label='Qual', ),
             Field('grupo_sanguineo_GA', label='Grupo Sanguineo', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Rh+', 'Rh-']))),
             Field('sensibilizada_GA', widget=SQLFORM.widgets.boolean.widget, label='Sensibilizada', ),
             Field('vacinacao_anti_tetanica',
                 widget=SQLFORM.widgets.boolean.widget, label='Vacinação anti-tetânica', ),
             Field('doses_previas', label='Doses Prévias', requires=IS_EMPTY_OR(IS_IN_SET(
                 [1, 2, 3]))),
             Field('ultima_dose_maior_cinco_anos_GA', label='Última dose > 5 anos',
                     requires=IS_EMPTY_OR(IS_IN_SET(
                         ['Sim', 'Não', 'Ignorado']))),
             Field('data_prevista_vacinacoes_um_GA',
                     widget=SQLFORM.widgets.boolean.widget, label='Realizada', ),
             Field('data_prevista_vacinacoes_um_texto_GA', label='1ª',),
             Field('data_prevista_vacinacoes_dois_GA',
                     widget=SQLFORM.widgets.boolean.widget, label='Realizada',),
             Field('data_prevista_vacinacoes_dois_texto_GA', label='2ª',),
             Field('data_prevista_vacinacoes_tres_GA',
                     widget=SQLFORM.widgets.boolean.widget, label='Realizada',),
             Field('data_prevista_vacinacoes_tres_texto_GA',label='3ª'),
             Field('fumo_GA', widget=SQLFORM.widgets.boolean.widget, label='Fumo', ),
             Field('famo_quantos_GA', label='Quantos/Dias', ),
             Field('alcool_GA', widget=SQLFORM.widgets.boolean.widget, label='Álcool',) ,
             Field('alcool_frequencia_GA', label='Frequencia', ),
             Field('intercorrencias_primeira_consulta_GA', label='Intercorrências até 1ª Consulta', ),
             Field('peso_primeira_consulta_ED', label='Peso 1ª Consulta', ),
             Field('peso_previo_ED', label='Peso Prévio', ),
             Field('estatura_ED', label='Estatura', ),
             Field('ex_clinico_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget, label='Ex clínico: Normal', ),
             Field('ex_mamas_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget, label='Ex mamas: Normal',) ,
             Field('ex_ginecologico_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget, label='Ex.ginecológico: Normal', ),
             Field('achados_alterados_exames_ED', label='Achados alterados nos exames realizados', ),
            ),


db.define_table('ficha_clinica_de_uroginecologia',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('queixa_duracao_QD', type='text', label='Queixa e Duração', ),
             Field('perda_esforcos_QD', label='Perda Esforço', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Não', 'Mínimos esforços', 'Médios esforços',
                     'Grandes esforços']))),
             Field('perda_urina_constante_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Perda de urina constante', ),
             Field('incontinencia_urgencia_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Incontinência de urgência', ),
             Field('esvaziamento_incompleto_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Esvaziamento incompleto', ),
             Field('n_miccao_noite_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Nº de micção/noite', ),
             Field('n_miccao_dia_QD', widget=SQLFORM.widgets.boolean.widget, label='Nº de micção/dia', ),
             Field('dusria_QD', widget=SQLFORM.widgets.boolean.widget, label='Disúria', ),
             Field('urgencia_miccional_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Urgência miccional', ),
             Field('enurese_noturna_QD',
                 widget=SQLFORM.widgets.boolean.widget, label='Enurese noturna', ),
             Field('hematuria_QD', widget=SQLFORM.widgets.boolean.widget, label='Hematúria', ),
             Field('polaciuria_QD', widget=SQLFORM.widgets.boolean.widget, label='Polaciúria', ),
             Field('antecedentes_cirurgicos_urinarios_QD', type='text', label='Antecedentes Cirúrcicos Urinários', ),
             Field('vulva_EFE', label='Vulva',requires=IS_EMPTY_OR(IS_IN_SET(
                 ['NL', 'Atrofia', 'Dermatite']))),
             Field('procidencia_pva_EFE', label='Procidencia', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente',
                     'Não atinge o intróito vaginal ao esforço',
                     'Atinge o intróito vaginal ao esforço',
                     'Ultrapassa o intróito vaginal ao esforço',
                     'Ultrapassa o intróito vaginal no repouso']))),
             Field('procidencia_pvp_EFE', label='Procidencia PVP',requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Discreta', 'Moderada', 'Acentuada']))),
             Field('perda_urina_EFE', label='Perda de Urina', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Não',
                     'Posição ginecológica',
                     'Posição ortostática',
                     'Pequena quantidade',
                     'Grande quantidade']))),
             Field('rotura_perineal_EFE', label='Rotura perineal', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente', '1º grau', '2º grau', '3º grau']))),
             Field('prolapso_uterino_EFE', label='Prolapso uterino', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente', '1º grau', '2º grau', '3º grau']))),
             Field('sensibilidade_perineal_EFE', label='Sensibilidade perineal', ),
             Field('reflexo_anal_EFE', label='Reflexo anal', ),
             Field('reflexo_bulbocavernoso_EFE', label='Reflexo bulbocavernoso', ),
             Field('teste_cotonete_EFE', label='Teste de cotonete', ),
             Field('urinal_um_ES', label='Urinal I', ),
             Field('urocultura_ES', label='Urocultura', ),
             Field('repouso_ES', label='Repouso' ),
             Field('esforco_ES', label='Esforço', ),
             Field('mobilidade_ES', label='Mobilidade', ),
             Field('fluxo_medio_ES', label='Fluxo médio', ),
             Field('fluxo_maximo_ES', label='Fluxo máximo', ),
             Field('vol_urinario_ES', label='Volume urinário', ),
             Field('residuo_ES', label='Resíduo', ),
             Field('cv_primeiro_desejo_ES', label='Cv 1ºdesejo', ),
             Field('cv_maxima_ES', label='Cv máxima', ),
             Field('perda_urina_ES', label='Perda urina', ),
             Field('contracao_nao_inibida_ES', label='Concentração não inibida', ),
             Field('pressao_perda_ES', label='Pressão de perda', ),
             Field('pmfu_ES', label='PMFU', ),
             Field('cfu_ES', label='CFU', ),
             Field('cisroscopia_ES', type='text', label='Cisroscopia', ),
             Field('urografia_excretora_ES', type='text', label='Urografia excretora', ),
             Field('outros_ES', type='text', label='Outros', ),
             Field('evolucao', type='text', label='Evolução', ),
             Field('conduta', type='text', label='Conduta', ),
             Field('data_ES', label='Data', ),
             Field('observacoes', type='text', label='Observações', ),
            ),


db.define_table('ficha_de_anticoncepcao',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('insp_estatica_MAMAS', type='text', label='Insp. Estática', ),
             Field('insp_dinamica_MAMAS', type='text', label='Insp. Dinâmica', ),
             Field('palpacao_MAMAS', type='text', label='Palpação', ),
             Field('expressao_MAMAS', type='text', label='Expressão', ),
             Field('axilas_MAMAS', type='text', label='Axilas', ),
             Field('vagina_TOQUE', type='text', label='Vagina', ),
             Field('colo_TOQUE', type='text', label='Colo', ),
             Field('utero_TOQUE', type='text', label='Útero', ),
             Field('an_d_TOQUE', type='text', label='An.D', ),
             Field('an_e_TOQUE', type='text', label='An.E', ),
             Field('reto_TOQUE', type='text', label='Reto', ),
             Field('parametrios_TOQUE', type='text', label='Paramétrios', ),
             Field('pilificacao_OGE', type='text', label='Pilificaçãoo', ),
             Field('labios_OGE', type='text', label='Lábios', ),
             Field('clitoris_OGE', type='text', label='Clitóris', ),
             Field('ureta_OGE', type='text', label='Ureta', ),
             Field('gi_bartholin_OGE', type='text', label='GI. Bartholin', ),
             Field('himem_OGE', type='text', label='Himem', ),
             Field('pva_OGE', type='text', label='PVA', ),
             Field('pvp_OGE', type='text', label='PVP', ),
             Field('perineo_OGE', type='text', label='Períneo', ),
             Field('perda_urina_OGE', type='text', label='Perda urina', ),
             Field('vagina_ESPECULAR', type='text', label='Vagina', ),
             Field('colo_ESPECULAR', type='text', label='Coloe', ),
             Field('cont_vaginal_ESPECULAR', type='text', label='Cont. Vaginal', ),
            ),

db.define_table('retorno',
                Field('id_paciente', 'reference pacientes',
                      readable=False, writable=False),
                Field('texto', 'text', label='Retorno'),
                Field('data', label='Data', type='date', default=request.now,
                      requires=IS_DATE(format='%d-%m-   %Y'),
                      readable=False, writable=False),
                ),
