# TODO: Estes models são grandes demais pra ficarem sendo carregados em toda página.
# Criar um módulo separado para cada uma das tabelas e chamar apenas quando for usado.

db.define_table('ficha_clinica_mulher',
             Field('id_paciente', 'reference pacientes',
                   writable=False,readable=False),
             Field('queixa', type='text', label='Queixa', ),
             Field('hpma', type='text', label='HPMA', ),
             Field('cardiovascular_ISDA', label='Cardiovascular', ),
             Field('gastrointestinal_ISDA', label='Gastrointestinal', ),
             Field('urinario_ISDA', label='Urinário', ),
             Field('respiratorio_ISDA', label='Respiratório', ),
             Field('cardiovascular_AF', label='Cardiovascular', ),
             Field('endocrino_metabolico_AF', label='Endócrino/Metabólico', ),
             Field('cancer_AF', label='Câncer', ),
             Field('infeccao_AF', label='Infecção', ),
             Field('outros_AF', label='Outros', ),
             Field('clinicos_AP', label='Clínicos', ),
             Field('cirurgias_AP', label='Cirurgias', ),
             Field('tabagismo_AP', label='Tabagismo', ),
             Field('etilismo_AP', label='Etilismo', ),
             Field('medicacao_AP', label='Medicações', ),
             Field('outros_AP', label='Outros', ),
             Field('menarca_AM', label='Menarca', ),
             Field('ciclos_AM', label='Ciclos', ),
             Field('dum_AM', label='DUM', ),
             Field('dismenorreia_AM', label='Dismenorréia', ),
             Field('tpm_AM', label='TPM', ),
             Field('menopausa_AM',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Natural','Cirúrgica'])),
                   widget=SQLFORM.widgets.radio.widget,
                   label='Menopausa'),
             Field('primeiro_coito_AS', label='1º Coito', ),
             Field('numero_parceiros_AS', label='Nº parceiros', ),
             Field('libido_AS', label='Libido', ),
             Field('orgasmos_AS', label='Orgasmos', ),
             Field('anticoncepcao_AS', label='Anticoncepção', ),
             Field('corrimento_AG', label='Corrimento', ),
             Field('cirurgia_AG', label='Cirurgia', ),
             Field('cauterizacao_AG', label='Cauterização', ),
             Field('g_AO', label='G', ),
             Field('p_AO', label='P', ),
             Field('a_AO', label='A', ),
             Field('pnl_AO', label='PNL', ),
             Field('pc_AO', label='PC', ),
             Field('pf_AO', label='PF', ),
             Field('primeiro_parto_AO', label='1º parto', ),
             Field('ultimo_parto_AO', label='Último parto', ),
             Field('peso_rn_maior_AO', label='Peso RN (maior)', ),
             Field('amamentacao_AO', label='Amamentação', ),
             Field('puerperio_AO', label='Puerpério', ),
             Field('peso_EXAME', label='Peso', ),
             Field('alt_EXAME', label='Alt', ),
             Field('pa_EXAME', label='PA', ),
             Field('imc_EXAME', label='IMC', ),
             Field('ap_cardiovascular_EXAME', label='Ap. cardiovascular', ),
             Field('ap_respiratorio_EXAME', label='Ap. respiratório', ),
             Field('mmii_EXAME', label='MMII', ),
             Field('outros_EXAME', label='Outros', ),
             Field('abdome_EXAME', label='Abdome', ),
             Field('insp_estatica_MAMAS', label='Insp. Estática', ),
             Field('insp_dinamica_MAMAS', label='Insp. Dinâmica', ),
             Field('palpacao_MAMAS', label='Palpação', ),
             Field('expressao_MAMAS', label='Expressão', ),
             Field('axilas_MAMAS', label='Axilas', ),
             Field('pilificacao_OGE', label='Pilificação', ),
             Field('labios_OGE', label='Lábios', ),
             Field('clitoris_OGE', label='Clitóris', ),
             Field('ureta_OGE', label='Uretra', ),
             Field('gl_bartholin_OGE', label='Gl. Bartholin', ),
             Field('himen_OGE', label='Hímen', ),
             Field('procidencia_pva_OGE', label='Procidência PVA', ),
             Field('procidencia_pvp_OGE', label='PVP', ),
             Field('perineo', label='Períneo', ),
             Field('perda_urina', label='Perda urina', ),
             Field('vagina_OGI_TOQUE', label='Vagina', ),
             Field('colo_OGI_TOQUE', label='Colo', ),
             Field('utero_OGI_TOQUE', label='Últero', ),
             Field('an_d_OGI_TOQUE', label='AN. D', ),
             Field('na_e_OGI_TOQUE', label='NA. E', ),
             Field('parametrios_OGI_TOQUE', label='Paramétrios', ),
             Field('reto_OGI_TOQUE', label='Reto', ),
             Field('vagina_ESPECULAR', label='Vagina', ),
             Field('colo_ESPECULAR', label='Colo', ),
             Field('cont_vaginal_ESPECULAR', label='Cont. vaginal', ),
             Field('tracao_colo_OUTROS_EXAMES', label='Tração do colo', ),
             Field('histerometria_OUTROS_EXAMES', label='Histerometria', ),
             Field('diagnostico_clinico_OUTROS_EXAMES', label='Diagnóstico Clínico', ),
             Field('exames_solicitados_OUTROS_EXAMES', label='Exames solicitados', ),
             Field('conduta_OUTROS_EXAMES', label='Conduta', ),
),

db.define_table('ficha_clinica_de_climaterio',
             Field('id_paciente', 'reference pacientes',
                    writable=False,readable=False),
             Field('motivo_consulta', type='text', label='Motivo da consulta', ),
             Field('hipertensao', widget=SQLFORM.widgets.boolean.widget, label='Hipertensão', ),
             Field('hipertensao_texto', label='', ),
             Field('tireoidopatia', widget=SQLFORM.widgets.boolean.widget, label='Tireoidopatia', ),
             Field('tireoidopatia_texto', label='', ),
             Field('tromboflebite', widget=SQLFORM.widgets.boolean.widget, label='Tromboflebite', ),
             Field('tromboflebite_texto', label='', ),
             Field('gastriste_colocistopatia',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('gastriste_colocistopatia_texto', label='', ),
             Field('doenca_cardio_cerebrovascular',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('doenca_cardio_cerebrovascular_texto', label='', ),
             Field('nefropatia', widget=SQLFORM.widgets.boolean.widget, label='Nefropatia', ),
             Field('nefropatia_texto', label='', ),
             Field('cirugia', widget=SQLFORM.widgets.boolean.widget, label='Cirugia', ),
             Field('cirugia_texto', label='', ),
             Field('tabagismo', widget=SQLFORM.widgets.boolean.widget, label='Tabagismo', ),
             Field('tabagismo_texto', label='', ),
             Field('medicacao_em_uso',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('medicacao_em_uso_texto', label='', ),
             Field('atividade_fisica',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('atividade_fisica_texto', label='', ),
             Field('hepatopatia', widget=SQLFORM.widgets.boolean.widget, label='Hepatopatia', ),
             Field('hepatopatia_texto', label='', ),
             Field('cancer', widget=SQLFORM.widgets.boolean.widget, label='Câncer', ),
             Field('cancer_texto', label='', ),
             Field('etilismo', widget=SQLFORM.widgets.boolean.widget, label='Etilismo', ),
             Field('etilismo_texto', label='', ),
             Field('neuro_psquiatrico',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('neuro_psquiatrico_texto', label='', ),
             Field('cancer_de_mama',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_ovario',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_utero',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('cancer_de_colon',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('osteoporose', widget=SQLFORM.widgets.boolean.widget, label='Osteoporose', ),
             Field('cardio_cerebrovascular',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('outros_AF', widget=SQLFORM.widgets.boolean.widget, label='Outros', ),
             Field('menarca', widget=SQLFORM.widgets.boolean.widget, label='Menarca', ),
             Field('menarca_texto', label='', ),
             Field('ciclos_regulares',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('ciclos_regulares_texto', label='', ),
             Field('atividade_sexual',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('atividade_sexual_texto', label='', ),
             Field('dum', label='DUM', ),
             Field('g_AT', label='G', ),
             Field('p_AT', label='P', ),
             Field('a_AT', label='A', ),
             Field('pnl_AT', label='PNL', ),
             Field('pc_AT', label='PC', ),
             Field('pf_AT', label='PF', ),
             Field('idade_menopausa', label='Idade Menopausa', ),
             Field('tempo_menopausa', label='Tempo de Menopausa', ),
             Field('tipo_menopausa',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Natural',
                                                   'Cirúrgica',
                                                   'Radioterápica',
                                                   'Quimioterápia']),),),
             Field('histerectomia', widget=SQLFORM.widgets.boolean.widget, label='Histerectomia', ),
             Field('ooforectoma_bilateral',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('pipula', widget=SQLFORM.widgets.boolean.widget, label='Pilula', ),
             Field('pipula_texto', label='', ),
             Field('reposicao_hormonal',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('reposicao_hormonal_texto', label='', ),
             Field('peso', label='Peso', ),
             Field('altura', label='Altura', ),
             Field('imc', label='IMC', ),
             Field('pa', label='PA', ),
             Field('MAMAS_inspecao', label='Mamas: Inspeção', ),
             Field('MAMAS_palpacao', label='Palpação', ),
             Field('MAMAS_axila', label='Axila', ),
             Field('abdome', label='Abdome', ),
             Field('oge', label='OGE', ),
             Field('ogi_vagina', label='OGI – Vagina', ),
             Field('colo', label='Colo', ),
             Field('corpo_do_utero', label='Corpo do útero', ),
             Field('anexos', label='Anexos', ),
             Field('toque_retal', label='Toque retal', ),
             Field('teste_progesterona',
                   requires=IS_EMPTY_OR(IS_IN_SET(['Positivo',
                                                   'Negativo']),),
                   widget=SQLFORM.widgets.radio.widget),
             Field('teste_progesterona_data', label='Data', ),
             Field('colpocitologia_oncologica', label='Colpocitologia oncológica', ),
             Field('im', label='IM', ),
             Field('im_data', label='IM Data', ),
             Field('mamografia', label='Mamografia', ),
             Field('mamografia_data', label='Data', ),
             Field('glicemia', label='Glicemia', ),
             Field('colesterou_total', label='Colesterou total', ),
             Field('hdl', label='HDL', ),
             Field('ldl', label='LDL', ),
             Field('triglicerides', label='Triglicérides', ),
             Field('ultra_sonografia_transvaginal', label='Ultra-sonografia transvaginal', ),
             Field('ultra_sonografia_transvaginal_data', label='Data', ),
             Field('densitometria_ossea', label='Densitometria óssea', ),
             Field('densitometria_ossea_data', label='Data', ),
             Field('dosagens_hormonais', label='Dosagens Hormonais', ),
             Field('dosagens_hormonais_data', label='Data', ),
             Field('consulta_outro_especialista',
                   widget=SQLFORM.widgets.boolean.widget),
             Field('consulta_outro_especialista_texto', label='', ),
             Field('diagnostico_clinico', type='text', label='Diagnóstico clínico', ),
             Field('orientacao_terapeutica', type='text', label='Orientação terapêutica', ),
             Field('data_EVOLUCAO', label='Data', ),
             Field('pa_EVOLUCAO', label='PA', ),
             Field('peso_EVOLUCAO', label='Peso', ),
             Field('altura_EVOLUCAO', label='Altura', ),
             Field('imc_EVOLUCAO', label='IMC', ),
             Field('texto_EVOLUCAO', type='text', label='Observações', ),
),


db.define_table('ficha_clinica_de_anticoncepcao',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
                Field('queixa', type='text'),
                Field('hpma', type='text'),
                Field('hipertensao_arterial_AF',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('diabetes_AF', widget=SQLFORM.widgets.boolean.widget),
                Field('cardiopatia_AF',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('cancer_AF', widget=SQLFORM.widgets.boolean.widget),
                Field('tipo_cancer_AF'),
                Field('neurologico_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('cardiovasculares_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('hipertensao_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('flebites_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('trombose_venosa_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('diabetes_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('tireoide_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('outras_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('hepatite_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('colecistopatias_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('gonococcia_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('sifilis_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('hpv_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('hiv_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('outras_dst_AP'),
                Field('doencas_renais_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('doencas_hematologicas_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('anemia_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('a_falciforme_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('outras_doencas_AP'),
                Field('cancer_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('cirurgias_anteriores_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('alergias_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('transfusao_AP', widget=SQLFORM.widgets.boolean.widget),
                Field('tranquilizantes_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('antidepressivos_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('antibioticos_AP',
                    widget=SQLFORM.widgets.boolean.widget),
                Field('outros_medicacao_atual_AP'),
                Field('menarca_AM'),
                Field('dum_AM'),
                Field('dismenorreia_AM',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('tpm_AM', widget=SQLFORM.widgets.boolean.widget),
                Field('ciclo_menstrual_AM'),
                Field('gesta_AO'),
                Field('para_AO'),
                Field('espontaneos_AO'),
                Field('provocados_AO'),
                Field('ultimo_aborto_AO'),
                Field('intercorrencias_AO'),
                Field('normais_AO'),
                Field('cesareas_AO'),
                Field('forcepes_AO'),
                Field('primeiro_parto_AO'),
                Field('ultimo_parto_AO'),
                Field('aleitamento_AO'),
                Field('idade_primeira_relacao_HS'),
                Field('durante_ano_HS'),
                Field('ultimos_meses_HS'),
                Field('frequencia_relacoes_sexuais_HS', requires=IS_EMPTY_OR(
                    IS_IN_SET(['nenhuma', '1 relação semana',
                        '2 relações semana', '3 - 5 relações semana',
                        '5 relações semana', 'eventual semana']))),
                Field('orgamos_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('dispareunia_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('coito_anal_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('tabagismo_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('etilismo_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('drogas_HS', widget=SQLFORM.widgets.boolean.widget),
                Field('drogas_qual_HS'),
                Field('drogas_injetaveis_HS'),
                Field('ritmo_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('ritmo_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('ritmo_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diafragma_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diafragma_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diafragma_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('geleia_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('geleia_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('geleia_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('preservativo_masculino_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('preservativo_masculino_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('preservativo_masculino_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('camisinha_feminina_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('camisinha_feminina_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('camisinha_feminina_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diu_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diu_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('diu_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('pilula_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('pilula_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('pilula_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('injetavel_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('injetavel_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('injetavel_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('ligadura_tubaria_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('ligadura_tubaria_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('ligadura_tubaria_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('vasectomia_espontaneo_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('vasectomia_estimulado_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('vasectomia_uso_em_qualquer_momento_CAP',
                        widget=SQLFORM.widgets.boolean.widget),
                Field('qual_CAP'),
                Field('quanto_tempo_CAP'),
                Field('metodo_escolha_pacientes'),
                Field('indicacao_medica'),
                Field('metodo_anticoncepcional'),
                Field('observacoes', type='text'),
                ),


db.define_table('ficha_clinica_mastologia',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('d_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('e_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('tempo_meses_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('nodulo_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('dor_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('fluxo_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('inflamacao_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('treuma_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('assintomatica_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('outros_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('observacoes_QD'),
             Field('menarca_AT'),
             Field('idade_primeiro_AT'),
             Field('menopausa_AT'),
             Field('aleitamente_numero_total_AT'),
             Field('hormonios_AT', widget=SQLFORM.widgets.boolean.widget),
             Field('dum_AT'),
             Field('aco_AT', widget=SQLFORM.widgets.boolean.widget),
             Field('aco_text_AT'),
             Field('g_AT'),
             Field('p_AT'),
             Field('a_AT'),
             Field('trh_AT', widget=SQLFORM.widgets.boolean.widget),
             Field('trh_text_AT'),
             Field('alcoolismo_APF', widget=SQLFORM.widgets.boolean.widget),
             Field('alcoolismo_text_APF'),
             Field('tabagismo_APF', widget=SQLFORM.widgets.boolean.widget),
             Field('tabagismo_text_APF'),
             Field('biopsia_previa_APF',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('ap_APF'),
             Field('cancer_mama_APF', widget=SQLFORM.widgets.boolean.widget),
             Field('tratamento', requires=IS_EMPTY_OR(
                 IS_IN_SET(['conservador', 'radical', 'RT', 'QT', 'HT']))),
             Field('mae_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('materno_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('unilateral_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('avo_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('paterno_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('bilateral_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('tia_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('irma_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('prima_CM', widget=SQLFORM.widgets.boolean.widget),
             Field('idade_CM'),
             Field('observacoes_CM'),
             Field('endometrio_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('colon_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('ovario_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('tireoide_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('prostata_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('outros_OC', widget=SQLFORM.widgets.boolean.widget),
             Field('outros_text_OC'),
             Field('exame_fisico_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado', 'D', 'E']))),
             Field('inspecao_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'volume', 'P', 'M', 'G']))),
             Field('abaulamento_E', widget=SQLFORM.widgets.boolean.widget),
             Field('retracao_E', widget=SQLFORM.widgets.boolean.widget),
             Field('uiceracao_E', widget=SQLFORM.widgets.boolean.widget),
             Field('eritema_E', widget=SQLFORM.widgets.boolean.widget),
             Field('edema_E', widget=SQLFORM.widgets.boolean.widget),
             Field('edema_braco_E', widget=SQLFORM.widgets.boolean.widget),
             Field('palpacao_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'espessamento', 'nodulo']))),
             Field('consistencia_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['cistica', 'endurecimento', 'fibroelastico', 'lipomatosa']))
                 ),
             Field('mobilidade_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['móvel', 'fixo', 'Fáscia peitoral', 'Parede costal', 'pele']
                 ))),
             Field('superficie_E', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['regular', 'irregular']))),
             Field('fluxo_Ex', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['S', 'N', 'D', 'E']))),
             Field('cor_Ex', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['sangue', 'sero-sanguinolento', 'seroso', 'esverdeado',
                     'lacteo', 'cristalino']))),
             Field('multiductal_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('uniductal_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('linfonodos_axila_Ex',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('supre_clavicular_Ex',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('d_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('unico_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('moveis_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('isolado_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('e_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('multiplo_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('fixos_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('conglomerado_Ex', widget=SQLFORM.widgets.boolean.widget),
             Field('lesao_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 [1, 2, 3, 'D', 'E']))),
             Field('suspeita_clinica_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('mamografia_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('usg_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('citologia_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('paaf_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('bag_SC', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Benigno', 'Maligno', 'Suspeito', 'Inconclusivo',
                     'NR']))),
             Field('biopsia_SC', widget=SQLFORM.widgets.boolean.widget),
             Field('ap_SC'),
             Field('estadiamento_clinico'),
             Field('tnm'),
             Field('conduta'),
             Field('rx_torax', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('rx_torax_text'),
             Field('mapeamento_osseo', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('mapeamento_osseo_text'),
             Field('usg_abdominal', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('usg_abdominal_text'),
             Field('usg_pelvica', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['normal', 'alterado']))),
             Field('usg_pelvica_text'),
            ),


db.define_table('ficha_clinica_parto_e_puerperio',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('data_P'),
             Field('local_P'),
             Field('nivel_atencao_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['1 º', '2º', '3º', 'Domiciliar', 'Outro']))),
             Field('idade_gestacional_P'),
             Field('inicio_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Espontâneo', 'Induzido']))),
             Field('tipo_parto_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Fórcepe', 'Cesária', 'Cefálico', 'Pélvico',
                     'Único', 'Gemelar']))),
             Field('episiotomia_P', widget=SQLFORM.widgets.boolean.widget),
             Field('laceracao_P', widget=SQLFORM.widgets.boolean.widget),
             Field('delivramento_espontaneo_P',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('curagem_P', widget=SQLFORM.widgets.boolean.widget),
             Field('mae_rh_P', widget=SQLFORM.widgets.boolean.widget),
             Field('imunoglobulina_P', widget=SQLFORM.widgets.boolean.widget),
             Field('responsavel_parto_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Médico', 'Enfermeira', 'Auxiliar']))),
             Field('responsavel_outro_P'),
             Field('morte_fetal_P', widget=SQLFORM.widgets.boolean.widget),
             Field('morte_feta_gestacao_P',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('morte_feta_parto_P',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('morte_feta_ignorado_P',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('morte_feta_causa_P'),
             Field('medicaocoes_parto_P', type='text'),
             Field('intercorrencias_parto_P', type='text'),
             Field('sexo_RN',
                 requires=IS_EMPTY_OR(IS_IN_SET(['Masculino', 'Feminino']))),
             Field('apgar_RN',
                 requires=IS_EMPTY_OR(IS_IN_SET(['1º minuto', '5º minuto']))),
             Field('reanimacao_P', widget=SQLFORM.widgets.boolean.widget),
             Field('vdrl_P', widget=SQLFORM.widgets.boolean.widget),
             Field('tipagem_sanguinea_P'),
             Field('peso_P'),
             Field('idade_exame_fisico_P'),
             Field('peso_idade_gestacional_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['AIG', 'GIG', 'PIG']))),
             Field('exame_fisico_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Anormal']))),
             Field('exame_neurologico_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Normal', 'Anormal']))),
             Field('estatura_P'),
             Field('perimetro_cefalico_P'),
             Field('achados_anormais_P', type='text'),
             Field('alojamento_conjunto_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_memb_hialina_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_hemorragia_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_anomalia_congenita_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_aspiracao_meconial_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_hiperbilirrubinemia_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_apneia_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_outras_sindromes_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_convuncao_P',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('patologias_intercorrentes_outras_P', type='text'),
             Field('alta_rn_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Sadio', 'Transferido']))),
             Field('idadei_alta_P'),
             Field('transferencias_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['+ 24', '- 24']))),
             Field('transferencias_dias_P'),
             Field('idade_obito_dias_P'),
             Field('idade_obito_horas_P'),
             Field('causa_obito_P', type='text'),
             Field('sexo_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Masculino', 'Feminino']))),
             Field('alimentacao_P', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Mama', 'Mista', 'Artificial']))),
             Field('data_CP'),
             Field('queixas_CP', type='text'),
             Field('pa_CP'),
             Field('estado_geral_CP'),
             Field('mucosa_CP'),
             Field('mamas_CP'),
             Field('abdome_CP'),
             Field('exame_ginecologico_CP'),
             Field('aleitamento_materno_CP',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('barreira_CP', widget=SQLFORM.widgets.boolean.widget),
             Field('diu_CP', widget=SQLFORM.widgets.boolean.widget),
             Field('hormonal_oral_CP', widget=SQLFORM.widgets.boolean.widget),
             Field('hormonal_injetavel_CP',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('comportamental_CP',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('cirurgico_CP', widget=SQLFORM.widgets.boolean.widget),
             Field('nenhum_CP', widget=SQLFORM.widgets.boolean.widget),
             Field('orientacao_CP', type='text'),
            ),


db.define_table('ficha_clinica_pre_natal',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('AF_hipertencao_arterial_A',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('AF_diabetes_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AF_gemelidade_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AF_malformacao_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AF_outros_A', type='text'),
             Field('AP_hipertencao_arterial_A',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('AP_diabetes_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AP_cir_pelvica_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AP_cardiopatia_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AP_infc_urinaria_A',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('AP_malformacao_A', widget=SQLFORM.widgets.boolean.widget),
             Field('AP_outros_A', type='text'),
             Field('gestacao_AO'),
             Field('parto_AO'),
             Field('abortos_AO'),
             Field('ectopicas_AO'),
             Field('gemelares_AO'),
             Field('abortamentos_AO'),
             Field('espontaneos_AO'),
             Field('provocados_AO'),
             Field('com_curetagem_AO'),
             Field('partos_vaginais_AO'),
             Field('partos_cesarios_AO'),
             Field('nascidos_vivos_AO'),
             Field('nascidos_mortos_AO'),
             Field('filhos_vivos_atuais_AO'),
             Field('obitos_primeira_semana_AO'),
             Field('obitos_apos_primeira_semana_AO'),
             Field('causa_obitos_AO'),
             Field('peso_rn_AO'),
             Field('data_ultima_gestacao_AO'),
             Field('amamentacao_AO', widget=SQLFORM.widgets.boolean.widget),
             Field('amamentacao_duracao_AO'),
             Field('amamentacao_causa_insucesso_AO'),
             Field('intercorrencias_gestacoes_anteriores_AO'),
             Field('dum_GA'),
             Field('dpp_GA'),
             Field('duvida_GA', widget=SQLFORM.widgets.boolean.widget),
             Field('duvida_qual_GA'),
             Field('grupo_sanguineo_GA', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Rh+', 'Rh-']))),
             Field('sensibilizada_GA', widget=SQLFORM.widgets.boolean.widget),
             Field('vacinacao_anti_tetanica',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('doses_previas', requires=IS_EMPTY_OR(IS_IN_SET(
                 [1, 2, 3]))),
             Field('ultima_dose_maior_cinco_anos_GA',
                     requires=IS_EMPTY_OR(IS_IN_SET(
                         ['Sim', 'Não', 'Ignorado']))),
             Field('data_prevista_vacinacoes_um_GA',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('data_prevista_vacinacoes_um_texto_GA'),
             Field('data_prevista_vacinacoes_dois_GA',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('data_prevista_vacinacoes_dois_texto_GA'),
             Field('data_prevista_vacinacoes_tres_GA',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('data_prevista_vacinacoes_tres_texto_GA'),
             Field('fumo_GA', widget=SQLFORM.widgets.boolean.widget),
             Field('famo_quantos_GA'),
             Field('alcool_GA', widget=SQLFORM.widgets.boolean.widget),
             Field('alcool_frequencia_GA'),
             Field('intercorrencias_primeira_consulta_GA'),
             Field('peso_primeira_consulta_ED'),
             Field('peso_previo_ED'),
             Field('estatura_ED'),
             Field('ex_clinico_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('ex_mamas_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('ex_ginecologico_normal_ED',
                     widget=SQLFORM.widgets.boolean.widget),
             Field('achados_alterados_exames_ED'),
             Field('data_primeira_EG'),
             Field('ig_primeira_EG'),
             Field('peso_primeira_EG'),
             Field('pa_max_mim_primeira_EG'),
             Field('altura_uterina_primeira_EG'),
             Field('apresentacao_fetal_primeira_EG'),
             Field('movimentos_fetais_primeira_EG'),
             Field('bcf_primeira_EG'),
             Field('edema_mmii_primeira_EG'),
             Field('data_segunda_EG'),
             Field('ig_segunda_EG'),
             Field('peso_segunda_EG'),
             Field('pa_max_mim_segunda_EG'),
             Field('altura_uterina_segunda_EG'),
             Field('apresentacao_fetal_segunda_EG'),
             Field('movimentos_fetais_segunda_EG'),
             Field('bcf_segunda_EG'),
             Field('edema_mmii_segunda_EG'),
             Field('data_terceira_EG'),
             Field('ig_terceira_EG'),
             Field('peso_terceira_EG'),
             Field('pa_max_mim_terceira_EG'),
             Field('altura_uterina_terceira_EG'),
             Field('apresentacao_fetal_terceira_EG'),
             Field('movimentos_fetais_terceira_EG'),
             Field('bcf_terceira_EG'),
             Field('edema_mmii_terceira_EG'),
             Field('data_quarta_EG'),
             Field('ig_quarta_EG'),
             Field('peso_quarta_EG'),
             Field('pa_max_mim_quarta_EG'),
             Field('altura_uterina_quarta_EG'),
             Field('apresentacao_fetal_quarta_EG'),
             Field('movimentos_fetais_quarta_EG'),
             Field('bcf_quarta_EG'),
             Field('edema_mmii_quarta_EG'),
             Field('data_quinta_EG'),
             Field('ig_quinta_EG'),
             Field('peso_quinta_EG'),
             Field('pa_max_mim_quinta_EG'),
             Field('altura_uterina_quinta_EG'),
             Field('apresentacao_fetal_quinta_EG'),
             Field('movimentos_fetais_quinta_EG'),
             Field('bcf_quinta_EG'),
             Field('edema_mmii_quinta_EG'),
             Field('data_sexta_EG'),
             Field('ig_sexta_EG'),
             Field('peso_sexta_EG'),
             Field('pa_max_mim_sexta_EG'),
             Field('altura_uterina_sexta_EG'),
             Field('apresentacao_fetal_sexta_EG'),
             Field('movimentos_fetais_sexta_EG'),
             Field('bcf_sexta_EG'),
             Field('edema_mmii_sexta_EG'),
             Field('data_setima_EG'),
             Field('ig_setima_EG'),
             Field('peso_setima_EG'),
             Field('pa_max_mim_setima_EG'),
             Field('altura_uterina_setima_EG'),
             Field('apresentacao_fetal_setima_EG'),
             Field('movimentos_fetais_setima_EG'),
             Field('bcf_setima_EG'),
             Field('edema_mmii_setima_EG'),
             Field('data_oitava_EG'),
             Field('ig_oitava_EG'),
             Field('peso_oitava_EG'),
             Field('pa_max_mim_oitava_EG'),
             Field('altura_uterina_oitava_EG'),
             Field('apresentacao_fetal_oitava_EG'),
             Field('movimentos_fetais_oitava_EG'),
             Field('bcf_oitava_EG'),
             Field('edema_mmii_oitava_EG'),
             Field('data_nona_EG'),
             Field('ig_nona_EG'),
             Field('peso_nona_EG'),
             Field('pa_max_mim_nona_EG'),
             Field('altura_uterina_nona_EG'),
             Field('apresentacao_fetal_nona_EG'),
             Field('movimentos_fetais_nona_EG'),
             Field('bcf_nona_EG'),
             Field('edema_mmii_nona_EG'),
             Field('data_decima_EG'),
             Field('ig_decima_EG'),
             Field('peso_decima_EG'),
             Field('pa_max_mim_decima_EG'),
             Field('altura_uterina_decima_EG'),
             Field('apresentacao_fetal_decima_EG'),
             Field('movimentos_fetais_decima_EG'),
             Field('bcf_decima_EG'),
             Field('edema_mmii_decima_EG'),
             Field('tipo_sanguineo_EL'),
             Field('hbht_EL'),
             Field('glicenia_jejum_EL'),
             Field('totg_EL'),
             Field('vdrl_EL'),
             Field('hbsag_EL'),
             Field('hiv_EL'),
             Field('toxoplasmose_EL'),
             Field('rubeola_EL'),
             Field('urinal_EL'),
             Field('urocultura_EL'),
             Field('papanicolaou_EL'),
             Field('outros_EL'),
             Field('data_US'),
             Field('ig_dum_US'),
             Field('ig_usg_US'),
             Field('peso_fetal_US'),
             Field('placenta_US'),
             Field('liquido_US'),
             Field('outros_US'),
             Field('observacoes_US', type='text'),
             Field('data_US'),
             Field('intercorrencias_conduta_US'),
            ),


db.define_table('ficha_clinica_de_uroginecologia',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('queixa_duracao_QD', type='text'),
             Field('perda_esforcos_QD', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Não', 'Mínimos esforços', 'Médios esforços',
                     'Grandes esforços']))),
             Field('perda_urina_constante_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('incontinencia_urgencia_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('esvaziamento_incompleto_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('n_miccao_noite_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('n_miccao_dia_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('dusria_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('urgencia_miccional_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('enurese_noturna_QD',
                 widget=SQLFORM.widgets.boolean.widget),
             Field('hematuria_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('polaciuria_QD', widget=SQLFORM.widgets.boolean.widget),
             Field('antecedentes_cirurgicos_urinarios_QD', type='text'),
             Field('vulva_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['NL', 'Atrofia', 'Dermatite']))),
             Field('procidencia_pva_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente',
                     'Não atinge o intróito vaginal ao esforço',
                     'Atinge o intróito vaginal ao esforço',
                     'Ultrapassa o intróito vaginal ao esforço',
                     'Ultrapassa o intróito vaginal no repouso']))),
             Field('procidencia_pvp_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Discreta', 'Moderada', 'Acentuada']))),
             Field('perda_urina_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Não',
                     'Posição ginecológica',
                     'Posição ortostática',
                     'Pequena quantidade',
                     'Grande quantidade']))),
             Field('rotura_perineal_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente', '1º grau', '2º grau', '3º grau']))),
             Field('prolapso_uterino_EFE', requires=IS_EMPTY_OR(IS_IN_SET(
                 ['Ausente', '1º grau', '2º grau', '3º grau']))),
             Field('sensibilidade_perineal_EFE'),
             Field('reflexo_anal_EFE'),
             Field('reflexo_bulbocavernoso_EFE'),
             Field('teste_cotonete_EFE'),
             Field('urinal_um_ES'),
             Field('urocultura_ES'),
             Field('repouso_ES'),
             Field('esforco_ES'),
             Field('mobilidade_ES'),
             Field('fluxo_medio_ES'),
             Field('fluxo_maximo_ES'),
             Field('vol_urinario_ES'),
             Field('residuo_ES'),
             Field('cv_primeiro_desejo_ES'),
             Field('cv_maxima_ES'),
             Field('perda_urina_ES'),
             Field('contracao_nao_inibida_ES'),
             Field('pressao_perda_ES'),
             Field('pmfu_ES'),
             Field('cfu_ES'),
             Field('cisroscopia_ES', type='text'),
             Field('urografia_excretora_ES', type='text'),
             Field('outros_ES', type='text'),
             Field('evolucao', type='text'),
             Field('conduta', type='text'),
             Field('data_ES'),
             Field('observacoes', type='text'),
            ),


db.define_table('ficha_de_anticoncepcao',
                Field('id_paciente', 'reference pacientes',
                    writable=False, readable=False),
             Field('insp_estatica_MAMAS', type='text'),
             Field('insp_dinamica_MAMAS', type='text'),
             Field('palpacao_MAMAS', type='text'),
             Field('expressao_MAMAS', type='text'),
             Field('axilas_MAMAS', type='text'),
             Field('vagina_TOQUE', type='text'),
             Field('colo_TOQUE', type='text'),
             Field('utero_TOQUE', type='text'),
             Field('an_d_TOQUE', type='text'),
             Field('an_e_TOQUE', type='text'),
             Field('reto_TOQUE', type='text'),
             Field('parametrios_TOQUE', type='text'),
             Field('pilificacao_OGE', type='text'),
             Field('labios_OGE', type='text'),
             Field('clitoris_OGE', type='text'),
             Field('ureta_OGE', type='text'),
             Field('gi_bartholin_OGE', type='text'),
             Field('himem_OGE', type='text'),
             Field('pva_OGE', type='text'),
             Field('pvp_OGE', type='text'),
             Field('perineo_OGE', type='text'),
             Field('perda_urina_OGE', type='text'),
             Field('vagina_ESPECULAR', type='text'),
             Field('colo_ESPECULAR', type='text'),
             Field('cont_vaginal_ESPECULAR', type='text'),
            ),

db.define_table('retorno',
                Field('id_paciente', 'reference pacientes',
                      readable=False, writable=False),
                Field('texto', 'text'),
                Field('data', type='date', default=request.now,
                      requires=IS_DATE(format='%d-%m-%Y'),
                      readable=False, writable=False),
                ),


